site_name: KI Design Patterns
theme:
  name: material
  language: de
  palette:
    primary: white
    accent: grey
  font:
    text: Crimson Text  # Klassische Buch-Serifenschrift
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.integrate # Integriert das Inhaltsverzeichnis links/rechts für mehr Ruhe

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com
