site_name: KI Design Patterns
theme:
  name: material
  language: de
  palette:
    primary: white
    accent: grey
  font:
    text: Crimson Text
    code: Roboto Mono
  features:
    - navigation.sections
    - content.code.copy

# Hier definierst du die Struktur deiner Webseite
nav:
  - Home: index.md
  - KI Design Patterns: KI-Design-Patterns.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.mermaid_format

extra_javascript:
  - https://unpkg.com
extra_css:
  - https://googleapis.com
